name: "DataDog: Mute Monitor"

inputs:
  monitor_name:
    description: "The name of the monitor to unmute"
    required: true
  dd_api_key:
    description: The DataDog API Key to use
    required: true
  dd_application_key:
    description: The DataDog Application Key to use
    required: true

runs:
  using: "composite"
  steps:
    - run: ./unmute-monitor.sh "${{ inputs.monitor_name }}" ${{ inputs.dd_api_key }} ${{ inputs.dd_application_key }}
      working-directory: ${{ github.action_path }}
      shell: bash
