name: "Toggle Pingdom Check"

inputs:
  check_name:
    description: "The name of the check to toggle"
    required: true
  pause:
    description: "Boolean - whether to pause or unpause"
    default: 'true'
  pingdom_token:
    description: The Pingdom token to use
    required: true

runs:
  using: "composite"
  steps:
    - run: ./toggle-check.sh "${{ inputs.check_name }}" "${{ inputs.pause }}" "${{ inputs.pingdom_token }}"
      working-directory: ${{ github.action_path }}
      shell: bash
