name: "DataDog: Mute Monitor"

inputs:
  monitor_name:
    description: "The name of the monitor to mute"
    required: true
  duration_minutes:
    description: "The number of minutes the monitor should be muted"
    required: false
  dd_api_key:
    description: The DataDog API Key to use
    required: true
  dd_application_key:
    description: The DataDog Application Key to use
    required: true

runs:
  using: "composite"
  steps:
    - run: ./mute-monitor.main.kts "${{ inputs.duration_minutes }}" ${{ inputs.dd_api_key }} "${{ inputs.monitor_name }}" ${{ inputs.dd_application_key }}
      working-directory: ${{ github.action_path }}
      shell: bash
