name: Deploy to Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      ENV_SPECIFIC_SECRET:
        required: true

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: ${{ inputs.environment }}
    concurrency: ${{ inputs.environment }}-env
    env:
      ENV_SPECIFIC_SECRET: ${{ secrets.ENV_SPECIFIC_SECRET }}
    steps:

      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v3.0.1
        with:
          role-to-assume: arn:aws:iam::499333472133:role/GitHub-CDK-Deploy
          aws-region: us-east-1

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - run: ./deploy.sh wiremock-cloud ${{ inputs.environment }}

      - name: Run Datadog Synthetics tests
        uses: DataDog/synthetics-ci-github-action@v0.17.0
        with:
          api_key: ${{secrets.DD_SYNTHETIC_TESTS_API_KEY}}
          app_key: ${{secrets.DD_SYNTHETIC_TESTS_APP_KEY}}
          test_search_query: 'env:${{ inputs.environment }}'
