name: Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-release-notes:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.ADMIN_DEPLOY_KEY }}
            ${{ secrets.CDK_DEPLOY_KEY }}
            ${{ secrets.MOCK_HOST_DEPLOY_KEY }}
            ${{ secrets.MOTHERSHIP_DEPLOY_KEY }}
            ${{ secrets.UI_DEPLOY_KEY }}
      - run: ./create-release-notes.sh live >> $GITHUB_STEP_SUMMARY

  create-mock-host-release-notes:
    needs: create-release-notes
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.MOCK_HOST_DEPLOY_KEY }}
      - run: ./create-mock-host-release-notes.sh live >> $GITHUB_STEP_SUMMARY

  deploy-qa:
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy.yml@main
    with:
      environment: qa
    secrets: inherit

  deploy-qa-mock-hosts:
    needs: deploy-qa
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy-mock-hosts.yml@main
    with:
      github-environment: qa
      environment: qa
    secrets: inherit

  deploy-live:
    needs: [deploy-qa-mock-hosts, create-release-notes]
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy.yml@main
    with:
      environment: live
    secrets: inherit

  update-mock-host-release-notes:
    needs: deploy-live
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.MOCK_HOST_DEPLOY_KEY }}
      - run: ./create-mock-host-release-notes.sh live >> $GITHUB_STEP_SUMMARY

  deploy-live-mock-hosts:
    needs: [deploy-live, update-mock-host-release-notes]
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy-mock-hosts.yml@main
    with:
      github-environment: live-mock-hosts
      environment: live
    secrets: inherit
