name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    uses: wiremock/wiremock-cloud-versions/.github/workflows/deploy.yml@main
    with:
      environment: dev
    secrets: inherit

  deploy-qa:
    needs: deploy-dev
    uses: wiremock/wiremock-cloud-versions/.github/workflows/deploy.yml@main
    with:
      environment: qa
    secrets: inherit

  deploy-live:
    needs: deploy-qa
    uses: wiremock/wiremock-cloud-versions/.github/workflows/deploy.yml@main
    with:
      environment: live
    secrets: inherit
