name: Redeploy Dev

on:
  workflow_dispatch:

permissions: write-all

jobs:
  deploy-live:
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy.yml@main
    with:
      github-environment: live
      environment: live
      subdomain: ''
    secrets: inherit

  deploy-live-mock-hosts:
    needs: deploy-live
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy-mock-hosts.yml@main
    with:
      github-environment: live-mock-hosts
      environment: live
    secrets: inherit
