name: Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-release-notes:
    runs-on: ubuntu-20.04
    outputs:
      release_notes: ${{ steps.release_notes.outputs.release_notes }}
      slack_release_notes: ${{ steps.release_notes.outputs.slack_release_notes }}
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.ADMIN_DEPLOY_KEY }}
            ${{ secrets.CDK_DEPLOY_KEY }}
            ${{ secrets.MOCK_HOST_DEPLOY_KEY }}
            ${{ secrets.MOTHERSHIP_DEPLOY_KEY }}
            ${{ secrets.UI_DEPLOY_KEY }}
      - id: release_notes
        name: Store release notes in outputs and job summary
        run: |
          set -eu
          release_notes="$(./create-release-notes.sh live)"
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "release_notes<<$EOF" >> $GITHUB_OUTPUT
          echo "$release_notes" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "slack_release_notes<<$EOF" >> $GITHUB_OUTPUT
          echo "$release_notes" | sed 's/\[\([^]]*\)\](\([^)]*\))/<\2|\1>/g'  >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          echo "$release_notes" >> $GITHUB_STEP_SUMMARY

  create-mock-host-release-notes:
    needs: create-release-notes
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.MOCK_HOST_DEPLOY_KEY }}
      - run: ./create-mock-host-release-notes.sh live >> $GITHUB_STEP_SUMMARY

  deploy-qa:
    runs-on: ubuntu-20.04
    steps:
      - run: echo fake deploy-qa

  deploy-qa-mock-hosts:
    needs: deploy-qa
    runs-on: ubuntu-20.04
    steps:
      - run: echo fake deploy-qa-mock-hosts

  deploy-live-pre-approve:
    needs: [deploy-qa-mock-hosts, create-release-notes]
    environment: live-pre-approve
    concurrency: live-env
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    outputs:
      approver: ${{ steps.live-pre-approve-approver.outputs.approver }}
      release_issue: ${{ steps.create_release_issue.outputs.return }}
    steps:

      - uses: actions/checkout@v4

      - name: Get live-pre-approve approver
        id: live-pre-approve-approver
        run: |
          approver=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approvals" \
          | jq -r '.[] | select(.state == "approved" and (.environments[] | select(.name == "live-pre-approve"))) | .user.login') && \
          echo approver="$approver" >> $GITHUB_OUTPUT

      - name: Create an issue
        id: create_release_issue
        uses: actions/github-script@v7
        with:
          script: |
            return await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Live deploy of Deployment Pipeline #${{ github.run_number }}",
              body: ${{ toJSON(needs.create-release-notes.outputs.release_notes) }},
              assignee: "${{ steps.live-pre-approve-approver.outputs.approver }}"
            });

      - name: Publish to slack channel via bot token
        id: slack
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: 'C03H9267J9X'
          payload: |
            {
              "text": "Second approval required for <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|live deploy of Deployment Pipeline #${{ github.run_number }}>",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Second approval required for <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|live deploy of Deployment Pipeline #${{ github.run_number }}>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(needs.create-release-notes.outputs.slack_release_notes) }}
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  deploy-live:
    needs: deploy-live-pre-approve
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy.yml@main
    with:
      github-environment: live
      environment: live
      subdomain: ''
      pre-approve: true
    secrets: inherit

  close-deploy-issue:
    needs: deploy-live
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Get live approver
        id: live-approver
        run: |
          approver=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approvals" \
          | jq -r '.[] | select(.state == "approved" and (.environments[] | select(.name == "live"))) | .user.login') && \
          echo approver="$approver" >> $GITHUB_OUTPUT

      - name: Close the issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ needs.deploy-live-pre-approve.outputs.release_issue.number }},
              state: "closed",
              state_reason: "Approved by ${{ steps.live-approver.outputs.approver }} and deployed",
              body: ${{ toJSON(needs.create-release-notes.outputs.release_notes) }},
              assignees: [
                "${{ needs.deploy-live-pre-approve.outputs.approver }}",
                "${{ steps.live-approver.outputs.approver }}",
              ]
            });

  update-mock-host-release-notes:
    needs: deploy-live
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.MOCK_HOST_DEPLOY_KEY }}
      - run: ./create-mock-host-release-notes.sh live >> $GITHUB_STEP_SUMMARY

  deploy-live-mock-hosts:
    needs: [deploy-live, update-mock-host-release-notes]
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy-mock-hosts.yml@main
    with:
      github-environment: live-mock-hosts
      environment: live
    secrets: inherit
