name: Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-release-notes:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: ./create-release-notes.sh live
    with:
      github-token: ${{ secrets.SET_VERSION_TOKEN }}

  deploy-qa:
    uses: wiremock/wiremock-cloud-versions/.github/workflows/deploy.yml@main
    with:
      environment: qa
    secrets: inherit

  deploy-qa-mock-hosts:
    needs: deploy-qa
    uses: wiremock/wiremock-cloud-versions/.github/workflows/deploy-mock-hosts.yml@main
    with:
      github-environment: qa
      environment: qa
    secrets: inherit

  deploy-live:
    needs: deploy-qa-mock-hosts
    uses: wiremock/wiremock-cloud-versions/.github/workflows/deploy.yml@main
    with:
      environment: live
    secrets: inherit

  deploy-live-mock-hosts:
    needs: deploy-live
    uses: wiremock/wiremock-cloud-versions/.github/workflows/deploy-mock-hosts.yml@main
    with:
      github-environment: live-mock-hosts
      environment: live
    secrets: inherit
