name: Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-release-notes:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.ADMIN_DEPLOY_KEY }}
            ${{ secrets.CDK_DEPLOY_KEY }}
            ${{ secrets.MOCK_HOST_DEPLOY_KEY }}
            ${{ secrets.MOTHERSHIP_DEPLOY_KEY }}
            ${{ secrets.UI_DEPLOY_KEY }}
      - run: ./create-release-notes.sh live >> $GITHUB_STEP_SUMMARY

  create-mock-host-release-notes:
    needs: create-release-notes
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.MOCK_HOST_DEPLOY_KEY }}
      - run: ./create-mock-host-release-notes.sh live >> $GITHUB_STEP_SUMMARY

  deploy-qa:
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy.yml@main
    with:
      github-environment: qa
      environment: qa
      subdomain: qa
    secrets: inherit

  deploy-qa-mock-hosts:
    needs: deploy-qa
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy-mock-hosts.yml@main
    with:
      github-environment: qa
      environment: qa
    secrets: inherit

  authorise-deploy-live:
    runs-on: ubuntu-latest
    environment: live
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 862323
          private-key: ${{ secrets.SERVICE_APP_PRIVATE_KEY }}
          owner: Mahoney
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'wiremock-inc',
              repo: 'wiremock-cloud-deployment-pipeline',
              workflow_id: 'deploy-live.yml',
              ref: 'main'
            })
