name: Deploy to Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      github-environment:
        required: true
        type: string
      region:
        required: false
        type: string
        default: 'us-east-1'
      subdomain:
        required: true
        type: string
      pre-approve:
        type: boolean
        default: false
    secrets:
      ENV_SPECIFIC_SECRET:
        required: true

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: ${{ inputs.github-environment }}
    concurrency: ${{ inputs.github-environment }}-env
    env:
      ENV_SPECIFIC_SECRET: ${{ secrets.ENV_SPECIFIC_SECRET }}
    steps:

      - uses: actions/checkout@v4

      - name: Check for Unique Approvals
        id: unique_check
        if: inputs.pre-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the list of review events for this workflow run
          reviewers=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approvals" \
            | jq -r '.[] | select(.state == "approved" and any(.environments[]; .name | startswith("live"))) | .user.login' | sort -u)

          # Check if there are two unique reviewers
          reviewer_count=$(echo "$reviewers" | wc -l)
          echo "Reviewers: $reviewers"
          if [[ reviewer_count -lt 2 ]]; then
            echo "Insufficient unique reviewers, need 2 or more"
            # exit 1
          fi

      - uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::499333472133:role/GitHub-CDK-Deploy
          aws-region: ${{ inputs.region }}

      - uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

#      - run: ./deploy.sh -p wiremock-cloud -e ${{ inputs.environment }} -r ${{ inputs.region }} -s '${{ inputs.subdomain }}' cdk
