name: Deploy to Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      github-environment:
        required: true
        type: string
      region:
        required: false
        type: string
        default: 'us-east-1'
      subdomain:
        required: true
        type: string
    secrets:
      ENV_SPECIFIC_SECRET:
        required: true

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: ${{ inputs.github-environment }}
    concurrency: ${{ inputs.github-environment }}-env
    env:
      ENV_SPECIFIC_SECRET: ${{ secrets.ENV_SPECIFIC_SECRET }}
    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::499333472133:role/GitHub-CDK-Deploy
          aws-region: ${{ inputs.region }}

      - uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - run: ./deploy.sh -p wiremock-cloud -e ${{ inputs.environment }} -r ${{ inputs.region }} -s '${{ inputs.subdomain }}' cdk

      - name: Run Datadog Synthetics tests
        uses: DataDog/synthetics-ci-github-action@v1.13.0
        with:
          api_key: ${{secrets.DD_SYNTHETIC_TESTS_API_KEY}}
          app_key: ${{secrets.DD_SYNTHETIC_TESTS_APP_KEY}}
          test_search_query: 'env:${{ inputs.environment }} state:live'
