name: Deploy Mock Hosts to Environment

on:
  workflow_call:
    inputs:
      slack-body:
        type: string
        required: false
      github-environment:
        required: true
        type: string
      environment:
        required: true
        type: string
      region:
        required: false
        type: string
        default: 'us-east-1'
    secrets:
      ENV_SPECIFIC_SECRET:
        required: true

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: ${{ inputs.github-environment }}
    concurrency: ${{ inputs.github-environment }}-env
    env:
      ENV_SPECIFIC_SECRET: ${{ secrets.ENV_SPECIFIC_SECRET }}
    steps:

      - uses: actions/checkout@v4

      - name: Publish to slack channel via bot token
        if: "${{ inputs.slack-body != '' }}"
        id: slack_mock_hosts
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: C03H9267J9X
            text: "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Mock Host deployment of Deployment Pipeline #${{ github.run_number }}>"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Mock Host deployment of Deployment Pipeline #${{ github.run_number }}>"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ${{ toJSON(inputs.slack-body) }}

      - uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::499333472133:role/GitHub-CDK-Deploy
          aws-region: ${{ inputs.region }}

      - uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Temporarily mute DataDog monitor
        if: ${{ inputs.environment == 'live' }}
        uses: ./.github/actions/mute-monitor
        with:
          monitor_name: Warnings or Errors on WireMock Cloud
          duration_minutes: 30
          dd_api_key: ${{ secrets.DD_MUTE_MONITOR_API_KEY }}
          dd_application_key:  ${{ secrets.DD_MUTE_MONITOR_APP_KEY }}

      - run: ./deploy.sh -p wiremock-cloud -e ${{ inputs.environment }} -r ${{ inputs.region }} mock-hosts

      - name: Publish completion to Slack
        if: "${{ inputs.slack-body != '' }}"
        id: slack
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: C03H9267J9X
            text: "Deployment finished (Completed)",
            thread_ts: "${{ steps.slack_mock_hosts.outputs.ts }}",
            reply_broadcast: true
