name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - simple-semver-reset

jobs:
  deploy-dev:
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy.yml@main
    with:
      environment: dev
    secrets: inherit

  deploy-dev-mock-hosts:
    needs: deploy-dev
    uses: wiremock-inc/wiremock-cloud-deployment-pipeline/.github/workflows/deploy-mock-hosts.yml@main
    with:
      github-environment: dev
      environment: dev
    secrets: inherit
