name: Deploy Mock Hosts to Environment

on:
  workflow_call:
    inputs:
      github-environment:
        required: true
        type: string
      environment:
        required: true
        type: string
      region:
        required: false
        type: string
        default: 'us-east-1'
    secrets:
      ENV_SPECIFIC_SECRET:
        required: true

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: ${{ inputs.github-environment }}
    concurrency: ${{ inputs.github-environment }}-env
    env:
      ENV_SPECIFIC_SECRET: ${{ secrets.ENV_SPECIFIC_SECRET }}
    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::499333472133:role/GitHub-CDK-Deploy
          aws-region: ${{ inputs.region }}

      - uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - run: ./deploy.sh wiremock-cloud ${{ inputs.environment }} mock-hosts
