name: WireMock Cloud Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-20.04
    environment: Dev
    concurrency: dev-env
    steps:
      - uses: actions/checkout@v3
      - run: cat imagedefinitions.json

  deploy-qa:
    runs-on: ubuntu-20.04
    environment: QA
    concurrency: qa-env
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v3
      - run: cat imagedefinitions.json

  deploy-live:
    runs-on: ubuntu-20.04
    environment: Live
    concurrency: live-env
    needs: deploy-qa
    steps:
      - uses: actions/checkout@v3
      - run: cat imagedefinitions.json
