name: WireMock Cloud Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-20.04
    environment: Dev
    steps:
      - uses: actions/checkout@v3
      - run: cat imagedefinitions.json

  deploy-qa:
    runs-on: ubuntu-20.04
    environment: QA
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v3
      - run: cat imagedefinitions.json

  deploy-live:
    runs-on: ubuntu-20.04
    environment: Live
    needs: deploy-qa
    steps:
      - uses: actions/checkout@v3
      - run: cat imagedefinitions.json
