name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    uses: wiremock/wiremock-cloud-versions/.github/workflows/deploy.yml@main
    with:
      environment: dev
    secrets: inherit

  deploy-dev-mock-hosts:
    needs: deploy-dev
    uses: wiremock/wiremock-cloud-versions/.github/workflows/deploy-mock-hosts.yml@main
    with:
      environment: dev
    secrets: inherit
