name: Redeploy Dev

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: The service to update
        required: true
        options:
          - ui
          - mothership
          - cdk
          - mock-host
          - admin
      tag_name:
        type: string
        description: The tag of the remote image
        required: true
permissions: write-all

jobs:
  redeploy-dev:
    runs-on: ubuntu-latest
    steps:

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 862323
          private-key: ${{ secrets.SERVICE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ steps.generate-token.outputs.token }}

      - uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::499333472133:role/GitHub-CDK-Deploy
          aws-region: us-east-1

      - run: ./redeploy-dev.sh ${{ github.event.inputs.name }} ${{ github.event.inputs.tag_name }}
