name: WireMock Cloud Set Image Version

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
      image_uri:
        required: true
        type: string
      source_action:
        required: true
        type: string
      source_commit:
        required: true
        type: string

jobs:
  set-version:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.SET_VERSION_TOKEN }}

      - run: ./set-version.sh ${{ github.event.inputs.name }} ${{ github.event.inputs.image_uri }} ${{ github.event.inputs.source_action }} ${{ github.event.inputs.source_commit }}

      - uses: EndBug/add-and-commit@v9
        with:
          add: imagedefinitions.json
          message: Set ${{ inputs.name }} to ${{ inputs.image_uri }}
